sudo: required
dist: trusty

language: python
node_js:
  - "4.1"
python:
  - "3.4"

cache:
  pip: true
  directories:
    - node_modules
    - coalahtml/_coalahtml/bower_components

install:
  - sudo apt-get -y install python3-pip python-dev
  - pip install -U pip setuptools
  - npm install -g bower
  - npm install
  - cd coalahtml/_coalahtml
  - bower install
  - cd -
  # colorama needs to be upgraded to fix error when installed colorama 
  # version and required are different.
  - pip install colorama==0.3.7
  - pip install -r requirements.txt
  - pip install -r test-requirements.txt

script:
  - npm test
  - python -m pytest --cov
  - bash <(curl -s https://codecov.io/bash)
  - coala

notifications:
  email: false
